// GIVE ALL CREDIT TO ELK
// MY DSC IS @2elk !!
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    window.open("jumpscare.mp4", "_blank")
    location.reload()
    
